<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-DFEV0VQ" failures="5" tests="35" name="Addition" time="2.033" errors="0" timestamp="10 Jan 2021 06:37:13 GMT">
  <testcase classname="AdditionTest" name="testCase" time="0.004"/>
  <testcase classname="AdditionTest" name="testCase" time="0.001"/>
  <testcase classname="AdditionTest" name="testCase" time="0.0"/>
  <testcase classname="AdditionTest" name="testCase" time="0.0"/>
  <testcase classname="AdditionTest" name="testCase" time="0.0"/>
  <testcase classname="SubtractTest" name="testCase" time="0.0"/>
  <testcase classname="SubtractTest" name="testCase" time="0.0"/>
  <testcase classname="SubtractTest" name="testCase" time="0.0"/>
  <testcase classname="SubtractTest" name="testCase" time="0.0"/>
  <testcase classname="SubtractTest" name="testCase" time="0.0"/>
  <testcase classname="MultiplicationTest" name="testCase" time="0.0"/>
  <testcase classname="MultiplicationTest" name="testCase" time="0.0"/>
  <testcase classname="MultiplicationTest" name="testCase" time="0.0"/>
  <testcase classname="MultiplicationTest" name="testCase" time="0.0"/>
  <testcase classname="MultiplicationTest" name="testCase" time="0.0"/>
  <testcase classname="DivisionTest" name="testCase" time="0.001"/>
  <testcase classname="DivisionTest" name="testCase" time="0.0"/>
  <testcase classname="DivisionTest" name="testCase" time="0.0"/>
  <testcase classname="DivisionTest" name="testCase" time="0.0"/>
  <testcase classname="DivisionTest" name="testException" time="0.0"/>
  <testcase classname="SquareTest" name="testCase" time="0.0"/>
  <testcase classname="SquareTest" name="testCase" time="0.0"/>
  <testcase classname="SquareTest" name="testCase" time="0.001"/>
  <testcase classname="SquareTest" name="testCase" time="0.0"/>
  <testcase classname="SquareTest" name="testCase" time="0.0"/>
  <testcase classname="SquareRootTest" name="testCase" time="0.004"/>
  <testcase classname="SquareRootTest" name="testCase" time="0.0"/>
  <testcase classname="SquareRootTest" name="testCase" time="1.002">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testCase() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testCase() didn't finish within the time-out 1000
	at app//Calculator.squareRoot(Calculator.java:33)
	at app//SquareRootTest.testCase(SquareRootTest.java:8)
	at java.base@15.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base@15.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@15.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base@15.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base@15.0.1/java.lang.Thread.run(Thread.java:832)
... Removed 7 stack frames]]>
    </failure>
  </testcase>
  <testcase classname="SquareRootTest" name="testNegative" time="1.002">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.ArithmeticException but got org.testng.TestException: 
Expected exception java.lang.ArithmeticException but got org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testNegative() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.TestException: 
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
	... 25 more
	at app//Calculator.squareRoot(Calculator.java:33)
	at app//SquareRootTest.testNegative(SquareRootTest.java:21)
	at java.base@15.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base@15.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@15.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base@15.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base@15.0.1/java.lang.Thread.run(Thread.java:832)
... Removed 35 stack frames]]>
    </failure>
  </testcase>
  <testcase classname="PrimeTest" name="testCase" time="0.0"/>
  <testcase classname="PrimeTest" name="testCase" time="0.0"/>
  <testcase classname="PrimeTest" name="testCase" time="0.0"/>
  <testcase classname="PrimeTest" name="testCase" time="0.0">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;false&amp;gt; but was:&amp;lt;true&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<false> but was:<true>
	at PrimeTest.testCase(PrimeTest.java:8)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase>
  <testcase classname="PrimeTest" name="testCase" time="0.0">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;false&amp;gt; but was:&amp;lt;true&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<false> but was:<true>
	at PrimeTest.testCase(PrimeTest.java:8)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase>
  <testcase classname="PrimeTest" name="testCase" time="0.0">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;false&amp;gt; but was:&amp;lt;true&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<false> but was:<true>
	at PrimeTest.testCase(PrimeTest.java:8)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase>
</testsuite>
